from typing import Optional

from vcm_os.context.pack_builder import ContextPackBuilder
from vcm_os.context.prompt_composer import PromptComposer
from vcm_os.context.sufficiency import SufficiencyChecker
from vcm_os.codebase.ast_index import PythonASTIndexer
from vcm_os.codebase.symbol_graph import SymbolGraph
from vcm_os.graph.expander import GraphExpander
from vcm_os.llm_client import LLMClient
from vcm_os.memory.decay import DecayEngine
from vcm_os.memory.reader import MemoryReader
from vcm_os.memory.reflection import ReflectionEngine
from vcm_os.memory.reranker import Reranker
from vcm_os.memory.rewriter import QueryRewriter
from vcm_os.memory.router import MemoryRouter
from vcm_os.memory.scorer import MemoryScorer
from vcm_os.memory.writer import MemoryWriter
from vcm_os.project.code_index import CodeIndex
from vcm_os.project.decision_ledger import DecisionLedger
from vcm_os.project.error_ledger import ErrorLedger
from vcm_os.project.stale_checker import StaleChecker
from vcm_os.session.checkpoint import CheckpointManager
from vcm_os.session.restore import SessionRestorer
from vcm_os.session.store import SessionStore
from vcm_os.storage.sparse_index import SparseIndex
from vcm_os.storage.sqlite_store import SQLiteStore
from vcm_os.storage.vector_index import VectorIndex
from vcm_os.summaries.generator import SummaryGenerator
from vcm_os.verifier.consistency import ConsistencyVerifier

store: Optional[SQLiteStore] = None
vector_index: Optional[VectorIndex] = None
sparse_index: Optional[SparseIndex] = None
writer: Optional[MemoryWriter] = None
reader: Optional[MemoryReader] = None
router: Optional[MemoryRouter] = None
scorer: Optional[MemoryScorer] = None
rewriter: Optional[QueryRewriter] = None
reflection: Optional[ReflectionEngine] = None
decay: Optional[DecayEngine] = None
session_store: Optional[SessionStore] = None
checkpoint_manager: Optional[CheckpointManager] = None
restorer: Optional[SessionRestorer] = None
decision_ledger: Optional[DecisionLedger] = None
error_ledger: Optional[ErrorLedger] = None
code_index: Optional[CodeIndex] = None
stale_checker: Optional[StaleChecker] = None
graph_expander: Optional[GraphExpander] = None
pack_builder: Optional[ContextPackBuilder] = None
prompt_composer: Optional[PromptComposer] = None
sufficiency: Optional[SufficiencyChecker] = None
llm: Optional[LLMClient] = None
ast_indexer: Optional[PythonASTIndexer] = None
symbol_graph: Optional[SymbolGraph] = None
verifier: Optional[ConsistencyVerifier] = None
summary_gen: Optional[SummaryGenerator] = None
